### PR TITLE
Biolab Changes

### PR DESCRIPTION
**Pull request by gregboiczyk**
Updated the biolab to add recipes to convert clownfish and raw salmon into raw fish in order to buff the fish based diamond cauldron recipe a bit more.  Also added 256 raw salmon to the biolab creation cost

### CODE REVIEW

**Comment by ttk2** [comment]
I just merged a second buff from mattress, does this take that into
account?

**Comment by gregboiczyk** [comment]
He wrote it after I did, but we had discussed the changes so he took my fix
into account when writing his

**Comment by ttk2** [comment]
and that means what exactly?

**Comment by gregboiczyk** [comment]
His additional buff was balanced around my buff

**Pull request closed without merging**
