### PR TITLE
Fixed(Hopefully) the stained clay factory!

### PR DESCRIPTION
**Pull request by ribagi**
HARD_CLAY ends up not being the same thing as STAINED_CLAY.

### CODE REVIEW

**Comment by ribagi** [comment]
I found an other wrong name. :s It is Glass to Glass Panes

**Comment by ttk2** [comment]
how is the color of the output supposed to be identified, as far as I can see this would output the same block for every recepie.

**Comment by WildWeazel** [comment]
Durability determines the color.

**Comment by ttk2** [comment]
ok then this goes in testing tomorrow morning.

**Pull request merged**
