### PR TITLE
factory mod pull

### PR DESCRIPTION
**Pull request by rourke750**

### CODE REVIEW

**Comment by ttk2** [comment]
what exactly does this do? I can guess but I want to be sure.

**Comment by rourke750** [comment]
Nether factories

**Comment by ttk2** [comment]
that's verbose...

**Comment by rourke750** [comment]
This is exactly what is on civtest right now.

**Comment by ttk2** [comment]
can't merge, conflicts.

**Comment by rourke750** [comment]
I'm bad at git.  No idea how to fix.

**Pull request closed without merging**
