### PR TITLE
Fixed Errors

### PR DESCRIPTION
**Pull request by ribagi**
Craft_Bookshelfs:

String -> Paper

### CODE REVIEW

**Comment by WildWeazel** [comment]
Looks good. Kind of odd that they chose 8 chests instead of 64 planks as input, but it's still efficient.

**Comment by ribagi** [comment]
If you do planks, you would have do 8 different recipes because of different types of wood.

**Comment by WildWeazel** [comment]
Ahh that makes sense, ok I approve

**Comment by ttk2** [comment]
Can't we make something in factorymod that would allow wood to map to all
types of wood automatically?

**Pull request merged**
