### PR TITLE
Change mad scientist lab creation requirement

### PR DESCRIPTION
**Pull request by ghost**
Removed the silk touch shear requirement and changed it to a nether star so that existing beacons can't be used, while not increasing the cost too much more than that of silk touch books.

1 silk touch book is 100d minimum
1 beacon is 150d minimum, but the price seems to be 300d according to civcraftexchange.

### CODE REVIEW

**Comment by ariehkovler** [comment]
I actually prefer the non-renewability of the ST book here to the AFK-portal-farm-grind of a Nether Star.

**Comment by ghost** [comment]
I don't have too much preference either way, the other pull request 
changes it to use a silk touch book instead, but according to pruby that 
actually might require a bit more work. Some people have expressed 
preference for not using silk touch book, but haven't seen many 
suggestions from people. It might be preferable to go with the silk 
touch book, since people tend to overestimate the expense and 
underestimate the ability of groups to overcome that expense.

**Comment by ttk2** [comment]
why was this one closed?

**Comment by ghost** [comment]
Some additional modification to factorymod is needed for it to be able 
to correctly read the metadata of the enchantment book. Pruby's pull 
request should add both that and the config changes. It does use 
stored_enchantment instead of enchantment, but according to pruby this 
should be the proper config option.

**Pull request closed without merging**
