### PR TITLE
Fix Handling of Enchanted Books as Inputs to Create Factories

### PR DESCRIPTION
**Pull request by totemo**
After adding more tracing I discovered that FactoryModPlugin.createItemStack()
was not using the storedEnchants argument due to a faulty if-condition.
Trivial fix.

Tested with a custom "String Recycler" factory that requires wool and a Silk Touch book to create because the Mad Scientist Factory takes too long to set up.

### CODE REVIEW

**Comment by totemo** [comment]
@erocs Ah yeah.  Will do.

**Comment by totemo** [comment]
One more thing: I did re-test the original Mad Scientist Laboratory with Silk Touch shears.  It's still particular about the repair cost of the shears, which depends on whether they were brand new or reconstituted from two damaged pairs.

**Comment by ttk2** [comment]
this all ready to be merged then?

**Comment by erocs** [comment]
Yes if the monster egg thing is right. Wasn't that just changed from monster egg to spawn egg?

**Comment by ghost** [comment]
For bukkit, MONSTER_EGG does seem to be correct.

**Comment by ttk2** [comment]
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Pigmen.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Pigmen.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Pigmen.outputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Infect_Zombies.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Infect_Zombies.outputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Skeletons.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Skeletons.outputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Creepers.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Creepers.outputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Witches.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Witches.outputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Spiders.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Spiders.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Spiders.outputs
requires invalid material SPAWN_EGG

production_recipes.Mutate_Cave_Spiders.inputs requires invalid material
SPAWN_EGG

production_recipes.Mutate_Cave_Spiders.outputs requires invalid material
SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Ghasts.inputs
requires invalid material SPAWN_EGG
[08:21:34 ERROR]([FactoryMod]): [FactoryMod] production_recipes.Mutate_Ghasts.outputs
requires invalid material SPAWN_EGG

production_factories.Mad_Scientist_Lab.inputs requires invalid material
SPAWN_EGG

production_factories.Mad_Scientist_Lab.inputs requires invalid material
SPAWN_EGG

production_factories.Mad_Scientist_Lab.inputs requires invalid material
SPAWN_EGG

production_factories.Mad_Scientist_Lab.inputs requires invalid material
SPAWN_EGG

production_factories.Mad_Scientist_Lab.repair_inputs requires invalid
material SPAWN_EGG

production_factories.Mad_Scientist_Lab.repair_inputs requires invalid
material SPAWN_EGG

production_factories.Mad_Scientist_Lab.repair_inputs requires invalid
material SPAWN_EGG

production_factories.Mad_Scientist_Lab.repair_inputs requires invalid
material SPAWN_EGG

well need a pull to fix that.

**Comment by erocs** [comment]
We shouldn't need another pull. ee16eab converted it to using MONSTER_EGG which is appropriate. Was the config updated on the server?

**Comment by ttk2** [comment]
oh no, I did not update the server config, that would be it.

**Pull request merged**
