### PR TITLE
Update FactoryModPlugin.java with the actual code :/

### PR DESCRIPTION
**Pull request by jjj5311**
Actually put the factorymodplugin.java code into this file this time...

### CODE REVIEW

**Comment by WildWeazel** [comment]
What about FactoryObject.java, was it supposed to have any changes? The only thing the previous pull had was a newline at the end.

**Comment by jjj5311** [comment]
good catch!

**Comment by ttk2** [comment]
so what do I do with this pull?

**Comment by jjj5311** [comment]
I think you should merge this and this should allow it to build

**Comment by WildWeazel** [comment]
It looks right

**Pull request merged**
