### PR TITLE
Ribagi's system with amended costs

### PR DESCRIPTION
**Pull request by pruby**
Amended Ribagi's system with higher costs, especially increasing the costs of construction and maintenance. Added extra costs to repair, removed some from each of construction and use so that they differ a bit (have to plan for costs to run before building if you want to be effective). Also, fixed some indentation, couple of typos, and it's "objet d'art", not "object d'art". Substantial test recommended.

**Add to Fancy Ore Smelter**

```
    4 Walls for 8 Lapis ore, 32 smooth brick
```

**Add to Ore Smelter**

```
    1 Base for 16 Diamond ore, 32 redstone ore
```

**Add to Iron Forge**

```
    1 Gearbox for 4 Iron blocks, 8 gold ore
```

**Add to Stained Glass Factory**

```
    1 Objet d'art for 16 of each dye, 256 red sand
```

**Add to Carpentry Factory**

```
    1 Framing for 64 Chests, 4 iron blocks
```

**Add to Stone Brick Smelter**

```
    1 Flooring for 64 Nether Brick, 32 clay ball
```

**Add to Grill**

```
    32 Rations for 256 Wheat, 32 bowls
```

**Add to Iron Cauldron**

```
    16 Smaragdus for 16 Emerald block (slow - 32 charcoal)
```

**Add to Explosives Factory**

```
    8 Silicon Tetranitratobihydrotrioxycarbon for 8 gunpowder, 32 quartz, 32 dirt, 8 coal block, 2 water buckets
```

**Add to Crystallization Factory**

```
    8 Pure ice for 512 Compact ice, 32 leather
```

**Bastion Factory** - 64 Silicon Tetranitratobihydrotrioxycarbon, 64 Smaragdus, 8 Flooring, 8 Framing, 8 Gearbox, 8 Base, 32 Walls

```
    Full repair for 16 Pure ice, 16 Silicon Tetranitratobihydrotrioxycarbon, 16 Smaragdus

32 Bastions (sponges) for 16 Silicon Tetranitratobihydrotrioxycarbon, 2 Smaragdus, 16 Rations, 1 Flooring, 1 Framing, 1 Objet d'art, 1 Gearbox, 1 Base, 4 Walls
```

Total raw materials in construction: 64 gunpowder, 256 quartz, 256 dirt, 64 coal block, 16 water buckets, 64 emerald blocks, 512 chests, 64 iron blocks, 512 nether brick, 256 clay ball, 64 gold ore, 128 diamond ore, 256 redstone ore, 64 lapis ore, 256 smooth brick

Total raw materials per full repair: 1024 packed ice, 64 leather, 16 gunpowder, 64 quartz, 64 dirt, 16 coal blocks, 4 water buckets, 16 emerald blocks

Total raw materials per run: 16 gunpowder, 64 quartz, 64 dirt, 16 coal blocks, 4 water buckets, 2 emerald blocks, 128 wheat, 16 bowls, 64 nether brick, 32 clay ball, 64 chests, 8 iron blocks, 16 of each dye, 256 red sand, 8 gold ore, 16 diamond ore, 32 redstone ore, 8 lapis ore, 32 smooth brick

Total raw materials per bastion: 1/2 gunpowder, 2 quartz, 2 dirt, 1/4 coal blocks, 1/8 water buckets, 1/16 emerald blocks, 4 wheat, 1/2 bowls, 2 nether brick, 1 clay ball, 2 chests, 1/4 iron blocks, 1/2 of each dye, 8 red sand, 1/4 gold ore, 1/2 diamond ore, 1 redstone ore, 1/4 lapis ore, 1 smooth brick

So the goal of having the factory expensive and the bastions effective to sell seems plausible.

### CODE REVIEW

**Comment by ttk2** [comment]
[09:43:51 ERROR]: Cannot load plugins/FactoryMod/config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 6842, column 3:
      Bastion_Gearbox
      ^
could not found expected ':'
 in 'string', line 6843, column 9:
        name: Gearbox
            ^

```
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:149) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:114) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:176) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:150) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:144) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at com.github.igotyou.FactoryMod.FactoryModPlugin.initConfig(FactoryModPlugin.java:94) [FactoryMod.jar:?]
    at com.github.igotyou.FactoryMod.FactoryModPlugin.onEnable(FactoryModPlugin.java:64) [FactoryMod.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:350) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:390) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:460) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:380) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:348) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:325) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:281) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:186) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:437) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
```

**Comment by staygroovy57** [comment]
'Add to smelter' means which smelter? the Stone Smelter? 

This seems unclear, should be specified.

**Comment by ttk2** [comment]
how so?

**Comment by MonsWTF** [comment]
After getting access to test out the new factory recipes on CivTest I have a couple of the current issues that need to be tackled before the Bastion factory is fully viable, as well as some beef with the phrasing of one of the words, ordered from greatest to least importance:

Explosives Factory
- Changing the 'Default Name' to 'Tetranitratobihydrotrioxycarbon'.
- Replace 'Sulphur' with 'Gunpowder'
- Replace 'Quartz' with 'Nether Quartz' (Why is this ambiguous word used for intensely-specific recipes? I noticed this too briefly for the Printing Press)
- Recipe states that 32 Dirt is needed, but factory requires 32 Podzol
- Factory does not accept Podzol as Podzol.

Meat Bakery (I find using that name more hilarious than its real-life name Grill)
- Changing the 'Default Name' to 'Rations'
- Currently does not have the input requirements (free 32 rations at the moment)
- Before I leave this one on to the next factory, is it possible to change the output item from filled bowls of soup to something else less space-intensive, like empty bowls? These take up a lot of space, though I'm not sure if that is what you want with the rations.

Crystalization Factory
- No option to create Pure Ice (Not an immediate issue, but one for down the line)

Fancy Ore Smelter
- Changing the name 'Smooth Brick' with 'Cracked Stone Brick'

Iron Cauldron
- Changing the 'Default Name' to 'Smaragdus'

Carpentry Factory
- Changing the 'Default Name' to 'Framing'

Stone Brick Smelter
- Changing the 'Default Name' to 'Flooring'.

**Comment by ttk2** [comment]
ok then that all sounds great, is that all in this pull?

**Comment by pruby** [comment]
This needs another pull to fix. ribagi - are you doing that?

**Comment by MonsWTF** [comment]
@ttk2 Gah! >.< I didn't mean that I was working on the pull, as I'm not entirely sure where to start with those. I was just listing out all significant typos/mistakes that were found on the live CIvTest version as of yesterday's posting of it.

I have at the least been able to deduce that the Default Name is occurring due to the parentheses on the name of the factory recipes.

**Comment by ttk2** [comment]
ok then, tell me when you have a pull with some or all of these fixes so I
 can get it merged.

**Pull request merged**
