### PR TITLE
Fixed Colored Glass Factories

### PR DESCRIPTION
**Pull request by ribagi**
Hopefully for the last time.

Made it so that you don't have to waste dye mats to have the same inputs.

### CODE REVIEW

**Comment by WildWeazel** [comment]
Good call, those were completely useless recipes. However you also changed GLASS_PANE to GLASS, which makes those ones pretty inefficient. It should be glass to glass and pane to pane.

**Comment by ribagi** [comment]
The one problem with meta-programming is that if you forget one thing everything goes to shit. I just fixed it.

**Comment by ribagi** [comment]
Side note, Bukkit is very inconsistent with their naming system. THIN_GLASS and STAINED_GLASS_PANE by example.

**Comment by WildWeazel** [comment]
looks good

**Comment by ttk2** [comment]
Good to merge then?

**Comment by ribagi** [comment]
Yea, looks good to merge

**Pull request merged**
