### PR TITLE
Nether Factory Backend

### PR DESCRIPTION
**Pull request by jjj5311**

### CODE REVIEW

**Comment by ribagi** [comment]
You are missing the netherfactory header.

https://github.com/rourke750/FactoryMod-1/blob/master/config.yml#L86-L86

**Comment by ttk2** [comment]
so should I be merging this or not?

**Comment by rourke750** [comment]
I would merge it and just get a fixed config from iebagi.

**Comment by ttk2** [comment]
all that's missing are config values?

**Comment by rourke750** [comment]
Yea, I can even add it once you accept the pull.

**Comment by ttk2** [comment]
go for adding it then.

**Comment by WildWeazel** [comment]
Bad merge, no donut. FactoryModPlugin.java is still in a conflicted state and does not compile.

**Comment by jjj5311** [comment]
Crap

**Comment by ttk2** [comment]
so what do now?

**Comment by WildWeazel** [comment]
So after looking closer it's not a conflict, but the file has the wrong contents. FactoryModPlugin was overwritten by FactoryObject, while the latter shows no changes.

**Comment by jjj5311** [comment]
how does that happen?

**Comment by WildWeazel** [comment]
No idea, how did you do the merge?

**Comment by jjj5311** [comment]
I pulled it from ribagis repo and was just taking the changes only, he had
the error so that is where it started.

**Comment by WildWeazel** [comment]
Same problem, ProductionManager.java contains class ItemList
InteractionResponse may also have been missed

**Comment by jjj5311** [comment]
Should probably just revert everything I have no idea how it got so messed
up

**Comment by jjj5311** [comment]
Compiled working version, I will commit this to your branch ttk

**Pull request merged**
