### PR TITLE
Bastion Factory Update; Attempting to get rid of the errors.

### PR DESCRIPTION
**Pull request by MonsWTF**
Attempting to remove all remaining errors that are delaying the Bastion update for the CivTest, and eventually CivCraft, server.

### CODE REVIEW

**Comment by ttk2** [comment]
cool, I will merge and test this tomorrow.

**Comment by ttk2** [comment]
[09:37:59 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while scanning
for the next token
found character          '\t(TAB)' that cannot start any token. (Do
not use \t(TAB) for indentation)
 in 'string', line 261, column 1:

```
^

    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
```

~[spigot.jar:git-Spigot-1366]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:149)
~[spigot.jar:git-Spigot-1366]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:204)
[spigot.jar:git-Spigot-1366]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:154)
[spigot.jar:git-Spigot-1366]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:144)
[spigot.jar:git-Spigot-1366]
        at com.untamedears.realisticbiomes.RealisticBiomes.onEnable(RealisticBiomes.java:72)
[RealisticBiomes.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250)
[spigot.jar:git-Spigot-1366]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[spigot.jar:git-Spigot-1366]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[spigot.jar:git-Spigot-1366]
        at org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugin(CraftServer.java:462)
[spigot.jar:git-Spigot-1366]
        at org.bukkit.craftbukkit.v1_7_R2.CraftServer.enablePlugins(CraftServer.java:380)
[spigot.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.MinecraftServer.n(MinecraftServer.java:351)
[spigot.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.MinecraftServer.g(MinecraftServer.java:326)
[spigot.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.MinecraftServer.a(MinecraftServer.java:282)
[spigot.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:186)
[spigot.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:440)
[spigot.jar:git-Spigot-1366]
        at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
[spigot.jar:git-Spigot-1366]

**Comment by MonsWTF** [comment]
I don't know what's going on, I didn't even touch that part of the code. Can someone tell me what I need to be doing at this point? As I have no idea how to fix this now T_T

**Comment by ttk2** [comment]
obviously whatever text editor you are using is doing things your not aware
of, what are you using?

**Pull request merged**
