### PR TITLE
Stackable security notes

### PR DESCRIPTION
**Pull request by pruby**
This pull request allows people to combine security notes in to larger stacks. They can left and right click an enchanting table while holding the notes to combine multiple notes in to a single item and back out again.

Each time 4 notes are combined in to one of 4 times the value. This can be repeated to three levels - 4x, 16x, 64x. At the peak density, one note represents a stack of unpacked notes.

To combine notes, right click on an enchanting table with the security notes in your hand. The notes in your hand will be combined in to ones worth 4 times as much. To get the original notes back, left click on an enchanting table holding the multiplied notes. If you don't have enough inventory, you will drop the excess.

JAR is included in the pull. Testing should focus on usability, that it only works with security notes, and not being able to duplicate items. I can change the scale and/or block used to pack/unpack these if needed.

### CODE REVIEW

**Comment by ttk2** [comment]
so this is trying to make paper currency more practical?

**Comment by Sanwi** [comment]
Stop trying to make paper currency happen; it's never going to work.

The one and only advantage of paper currency is that it is less bulky/heavy than gold. This is clearly not a problem in Civcraft, and having a paper currency means you have to rely on someone who may or may not be trustworthy to back that currency, and to not cheat the system by printing extras.

**Comment by ghost** [comment]
The problem with paper currency in Civcraft is not a coding issue. It's a political issue. No amount of coding can make paper currency useful; it's in game politics and influence that does so. 

I'm sorry, but I don't understand the purpose of this fix. Paper currency is coded as well as it could be. If people aren't using it, it's because they can't implement it politically.

Again, I have successfully implemented a paper fiat currency in Civcraft, and it works. Few people seem to acknowledge this. Please leave security notes how they are now, I really don't want my currency damaged or modified simply because others cannot figure out how to climb aboard the fiat train.

**Comment by pruby** [comment]
It just makes security notes more stackable - have had a few people complain about real currency having a substantial weight advantage. This lets you store multiples of 64 up to 4096 in a slot by packing, and any number up to 4159 in two slots.

**Pull request merged**
