### PR TITLE
Wood cauldron nerf

### PR DESCRIPTION
**Pull request by ariehkovler**

### CODE REVIEW

**Comment by MonsWTF** [comment]
Looks intriguing. Is this nerf to strike towards the large-end farmers that collect wheat only via bots? I noticed a significant reduction in the value of wheat being reduced to 30% in comparison to the others going down by 50%.

**Comment by ariehkovler** [comment]
That's about the plan, yeah

**Comment by MonsWTF** [comment]
Huh, interesting. Is there a certain time frame we can expect this to get implemented?

**Comment by ttk2** [comment]
I would like to do so soon, but I do have some reservations about killing
efficacy of wheat, might be better to keep it as a component but add others
(this being in the higher tier factories)

**Comment by MonsWTF** [comment]
I may be asked to burn at the stake for this but...

I don't think the efficacy of wheat is the main issue here, but rather the efficiency of it in comparison to every other recipe in-game, and the ease at which players find it for establishing the economy. Consider that a few of the well established towns in the game have plenty of large tracts of wheat fields strictly dedicated towards exp production. 50% of the Iron Cauldron recipes shrink in comparison to the effectiveness of simply gathering Wheat/Hay Bales, and even diamond cauldron usage gets hit partially. Why should I take the time to organize the infrastructure and/or trading arrangements to gather various materials, when I can just build an 85x85 Flat field of wheat and get the same amount per run of diamond recipes?

More importantly, is a mod working correctly to enhance the economy if one of its most basic factories can sometimes overpower the higher-end version? Does nerfing the Wooden cauldron mean only the lesser-developed cities take a hit, or is it also going to effect the well-established ones as well? Are the larger countries of the server able to adjust to this restriction on 'wheat efficacy', or to better phrase it, are they unable to arrange the means to operate a diverse economy of various resources?

**Comment by ttk2** [comment]
I don't think anyone is really unable to operate with harder recepies they
would just rather not, I am not out to destroy the value of wheat, but I do
want factorymod setup so that its not the only thing you need to do very
well, if you have just wheat sure we will give you somthing but it should
be not very much compared to a more diversified investment.

**Comment by ariehkovler** [comment]
At the moment, wheat is used by pretty much everyone, including top-tier
cities and groups.

Even this nerf might not be enough to stop that, but it's a start.

**Comment by MonsWTF** [comment]
Oh. This nerf would probably be big enough to stop most of the low-end farming for a majority of the players that make their moneys-worth off of it and their bots. Even if people still use wheat after this, it's enough of a reduction that players can get an extreme benefit by upgrading to Iron or Diamond cauldrons, though the impact this will have for the short term supply of items will be interesting to say the least, not to mention what we'll see in the long term.

**Comment by ribagi** [comment]
To be honest, it feels like this nerf is just so large it needs to come online with minor buffs to iron and major buffs  to diamond factories.

**Comment by ariehkovler** [comment]
I disagree. Nerfing is much harder and less popular than buffing. If a
diamond cauldron buff becomes needed, we can put it on later. But I'd
rather not buff an XP production method until we see how this pans out.

**Comment by ribagi** [comment]
There is a reason why people are not using the Diamond and Iron little to none at all. To me it is because they are not worth the effort. I can only predict that simply nerfing the wood recipe would only result in less xp in the economy. That is unless that is the goal of this.

**Comment by MonsWTF** [comment]
Sure, you could say that the nerf would lead to less exp in the economy. However, consider: if the economy shrinks in Emerald block supply, then doesn't that mean that a large percentage of the server's biggest, or consistent, emerald suppliers were strictly relying on wheat and the other wooden cauldron recipes?

To say it again as it has been said previously, the reason that Wheat was in the light of being nerfed was the combination of easiness and effectiveness in comparison to Iron and Diamond. You question why the diamond cauldron is so minimally used? If performing an easy task can provide as much reward as a difficult task, then what is the incentive to take up the latter? Upon that logic,  why spend the time to gather a variety of resources, when I can just focus on a single one and get the same returns for a bit or repetition?

The nerf is not to lessen the supply, but to re-value the significance of the diamond/iron cauldrons and the benefit of having a diversified economy, as opposed to relying on just one resource. Merchants that sell exp would not give up so easily, and would be ready to transition into upgrading to maintain their income. The SRAS may shrink, but I doubt the LRAS will sustain any significant change, if not increasing, as it has been.

**Comment by ariehkovler** [comment]
They aren't worth the effort because bots on wheat farms produce enough XP
for anyone who want it. It's not worth the effort for people to diversify
into multicultures.

Producing XP was supposed to be mainly something people cooperated to do
over biomes. We only added the Wheat Cauldron at all because people felt
that hermits should have a way to produce a small amount of XP for
low-level enchants. Botting a single crop should never be as efficient as
diamond-scale production.

And it isn't, actually. Not even now. The most efficient way to make XP is
still the diamond cauldron. 6 people working together on each ingredient
can massively outproduce a wheat-bot farm. But it doesn't happen because
people prefer autarky and are prepared to accept some inefficiency in
return for self-sufficiency, security, privacy.

And that's also OK. But the balance is wrong at the moment. The amount of
inefficiency isn't high enough.

This nerf might result in less XP production, but it might even result in
more. Markets are complicated. And I don't really care either way, because
this isn't about the supply of XP.

Frankly I don't think this nerf will be enough to make a real change. I
think people will still bot wheat rather than cooperate. But it's a start.

**Comment by MonsWTF** [comment]
While I agree with most of your points, I can't entirely say that your third statement is hitting the full scope. At one point, myself and the members of our town decided to invest in the resources needed to supply a Diamond factory. It soon eventually fell flat, as we determined that tracking down each of the materials, farming and gathering each, transporting them to the cauldron, and putting in the right amounts of each per run, was far more complicated than just grabbing wheat/Hay bales and dumping it en masse.

You are right when you say the balance is wrong and the inefficiency isn't high enough. Even if bots continue to operate, such a nerf will still be a big hit to curb that type of wealth production.

**Comment by ribagi** [comment]
Carson had a Diamond recipe running early this map. The idea was for efficiency and self-sufficiency. Carson stopped using the Diamond recipe because it was not worth it. The effort going it was not worth the effort going out. Greg would spend a whole day just hitting a furnace and inputting correct materials just to get a stack of blocks. I just got an idea for an alternative way which has Arieh's changes.

**Comment by ariehkovler** [comment]
I think it only wasn't worth it compared to botting wheat, because botting
wheat is no work whatsoever once it's set up.

**Comment by ribagi** [comment]
You still had to gather the glass/sand. Cliffnerd once offered me and a few other people 1/2 of what he was making if we got him glass/sand

**Comment by MonsWTF** [comment]
@Ribagi what, do you want to upgrade the Iron/Diamond Cauldrons and have the final emerald block be made in the cauldron from components?

... According to Ttk, he wants there to be a a significant gap between the low end and the high end cauldrons. I don't know if that means he wants the iron/diamond ones buffed as well (either by increasing the bottles or improving the ease of using them), or if nerfing the wooden one alone is all that we need to do.

**Comment by ribagi** [comment]
Yeah, I will handle it. It will be easy to just to divide by the amount of bottles in blocks.

I got an idea on how to make higher end cauldrons better, I might do a pull later.

**Comment by ttk2** [comment]
this all good to merge?

**Comment by ariehkovler** [comment]
I think so.

**Comment by ttk2** [comment]
merged, now we need to test it, _sigh_ trying to test the netherfactory and this at the same time will be a doozy, I could just put this online tomorrow?

**Comment by pruby** [comment]
Would test this before the nether factories, yes. This is a small change and unlikely to have bugs, NF just by sheer size is likely to.

**Comment by MonsWTF** [comment]
I can hop online and test out each of the recipes to make sure all of it is okay in a little bit.

**Comment by ttk2** [comment]
problem is we only have one testing server, I guess it will test this right
now.

**Comment by ttk2** [comment]
there we go, its in testing on civtest.

**Comment by MonsWTF** [comment]
Sorry for not replying here sooner.

Anyway, the Wood Cauldron appears to be acting normally for each of the recipes. It accepted the resources and output the new amount of Exp Potions at their new values without fault.

**Pull request merged**
