### PR TITLE
Backport 17 factories

### PR DESCRIPTION
**Pull request by pruby**
Backported the 1.7 factory config.yml, excluding the nether factory bits, however I can't update the Python config generator scripts to include the new factory types as apparently my Python version can't run them. Is anyone still using those scripts?

### CODE REVIEW

**Comment by ttk2** [comment]
probably not. so this contains the new config factories from the changelog?
minus or plus the netherfactory?

**Comment by pruby** [comment]
Yes, seems to have all those. It also has an explosives factory I don't recall seeing in the changelog, but is in documentation : https://github.com/poopdish/test_for_factorymod_config/wiki/Test1

**Comment by pruby** [comment]
This doesn't contain the nether factory or any of the config for that.

**Comment by ttk2** [comment]
ok then, merged this goes.

**Pull request merged**
