### PR TITLE
Change madlab requirement to silk touch book

### PR DESCRIPTION
**Pull request by ghost**
Removed repair_cost and the shear requirement. Replaced it with an enchanted book requirement.

### CODE REVIEW

**Comment by ghost** [comment]
Updated to remove the underscores from name in `Silk touch book:`

**Comment by pruby** [comment]
Need to use stored enchantments for a book - added support in potions pull never merged. Meaning to back port but busy weekend.

**Comment by pruby** [comment]
Can't amend this pull as not mine so added my own to do same thing, but use stored enchantments (books aren't enchanted in the same way items are) - https://github.com/ttk2/FactoryMod/pull/56

**Comment by ghost** [comment]
Pruby has amended this so this pull request is now unneeded.

**Pull request closed without merging**
