### PR TITLE
Added the colon

### PR DESCRIPTION
**Pull request by ribagi**
Were missing in a few areas.

### CODE REVIEW

**Comment by ttk2** [comment]
was that really it?

**Comment by pruby** [comment]
Gah, ran up on local server and looks like still a few syntax tweaks needed:

org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 7029, column 7:
          Silicon Tetranitratobihydrotriox ... 
expected <block end>, but found BlockMappingStart
 in 'string', line 7033, column 8:
           lore: An item used to create a B ... 
           ^
You want to get those, ribagi?

**Comment by ribagi** [comment]
There we go, it wasn't inline with everything else.

**Comment by pruby** [comment]
Confirmed no parse errors on load

**Comment by ttk2** [comment]
ok so do we need a new pull then?

**Comment by pruby** [comment]
This one can be merged - the original pull request author can amend until it's merged or cancelled.

**Pull request merged**
