### PR TITLE
Add Bastion Factory

### PR DESCRIPTION
**Pull request by pruby**
Too much discussion, not enough action. If nobody else will do the actual config, I'll suggest one that suits me :P .

```
**Bastion Factory** - 3328 Obsidian, 128 Sticky Pistons (full double chest)

32 Bastions (Sponge) for 64 Redstone Blocks, 64 Lapis Blocks, 64 Emerald Blocks, 64 Coal Blocks

Full repair costs 256 Emerald Blocks, 32 Sticky Pistons
```

This is a bit different to other factories as it has quite different construction, maintenance and use costs. The initial cost isn't too crippling other than requiring some coordination and preferably an advanced redstone factory, but the maintenance is designed as a burden which will require good logistics to collect the recipe inputs and regularly run to justify.

EDIT: Drop lapis cost - too high in ore
EDIT 2: Doubled maintenance - looks too light on review

### CODE REVIEW

**Comment by pruby** [comment]
When I look at it, the bastion recipe looks like a colour mixing exercise - red, green, blue and black.

**Comment by spaceFountain** [comment]
For context the creation cost in diamonds is:
- 52 diamonds from the Obsidian
- 10 stacks of diamonds from the Sticky Pistons (probably would go up as I this would make slime balls much more expensive).

Sum is 692

A run would cost:
- 32 diamonds from the Redstone
- About another 32 from the Lapis
- > 240 from the Emerald
- > 5 diamonds for the coal

For a sum of 277 diamonds for a run or 8.65 per block.

**Comment by pruby** [comment]
Note - the cheaper parts of the run are deliberately finite and non-renewable, whereas creation and maintenance are nearly fully renewable.

**Comment by pruby** [comment]
"10 stacks of diamonds from the Sticky Pistons" - about that without advanced redstone factory (128 slime balls required). About 4-5 stacks with the advanced redstone factory as it produces 2 sticky pistons per slime ball (64 slime balls required). The advanced redstone factory itself requires 128 slime balls to build though, so can build:
- Only advanced redstone, 128 slime ball construction + 10 per repair
- Only bastion factory, 128 slime ball construction + 32 per repair
- Both, 192 slime ball construction + 26 repair

All three are viable choices based on up front cost and ongoing maintenance. Or, buy and sell sticky pistons from someone else with the advanced redstone factory. Creates trade-offs.

**Comment by spaceFountain** [comment]
All the values were based on searching for the items on /r/civcraftExchange. I’m not sure how accurate it is, but the quote given was 5 diamond for a stick piston with about 4.5 of that going to the slime ball. Your probable right in saying then the price would go down with higher volumes as factories began to make sense.

**Comment by spaceFountain** [comment]
It's been asked that I point people to [this thread](http://www.reddit.com/r/Civcraft/comments/21d48q/discussion_how_much_should_bastion_blocks_and/)

**Comment by ghost** [comment]
Thanks! I just made an account too, hooray. I wanted to say that I think the obsidian is probably not a great idea since it is highly bottable (and is in fact one of the most botted products on the server)

**Comment by ghost** [comment]
interesting. it still has the massive obby cost (I still think we might be better served by unbottable unrenewable dirt) - how would one even start a villager farm? and is it possible that this would create strain on the server due to people maintaining loaded chunks with npc farms more than there already are with things like portal farms?

**Comment by staygroovy57** [comment]
Researching actual prices on slimeballs, at this moment the prices oscillate between 3 ~ 4 d each.
Additionally, and if it's any interest the recipe for sticky pistons has changed and now delivers 32 sticky pistons for 16 slimeballs. (lower entry point as far as quantities)

**Pull request closed without merging**
