### PR TITLE
Changing Input Names

### PR DESCRIPTION
**Pull request by ribagi**
For some reason, I put <COLOR> Stained Clay besides Harden Clay when I made this factory. This shouldn't cause any major issues besides people being confused.

### CODE REVIEW

**Comment by ttk2** [comment]
hey, with all the YAML issues right now can we get a rundown on what your
config is based off of? it could just reintroduce errors we are trying to
squash.

**Comment by ribagi** [comment]
It is just renaming the items the factory calls the material being imputed. 

Also there was no header for stained clay factory. I just copied the Stained Glass factory and replaced all the references to glass to clay.

**Comment by ttk2** [comment]
can we fix the config in the .jar?

**Comment by pruby** [comment]
Hi ttk,

Please could you merge any of these pull requests that can be auto-merged, then I'll do a run through of the config, check for errors and build a JAR. Ribagi - everything needed in - typos, etc?

**Comment by ttk2** [comment]
all merged, go crazy.

**Pull request merged**
