### PR TITLE
Remove compactor recipes from iron cauldron

### PR DESCRIPTION
**Pull request by pruby**
Before:

```
pruby@thorn:~/dev/FactoryMod$ ruby validate_config.rb
Missing recipes:
  ["Iron_XP_Bottle_4", "Iron_XP_Bottle_5", "Iron_XP_Bottle_6", "Iron_XP_Bottle_7"]
```

After this change:

```
pruby@thorn:~/dev/FactoryMod$ ruby validate_config.rb
OK
```

### CODE REVIEW

**Comment by ttk2** [comment]
you think this was out latest config issue?

**Comment by pruby** [comment]
The validation script returns clean, which means the file is valid yaml, all recipes referenced are there, and all material names are valid Bukkit material names. Gives a good degree of confidence - suggest should be run on all FM configs before release.

Sent from Samsung Mobile

-------- Original message --------

**Comment by ttk2** [comment]
where is a copy of this script?

**Comment by pruby** [comment]
It's in the repository - wrote it in Ruby.

> ruby validate_config.rb

**Pull request merged**
