### PR TITLE
Extended tech tree for XP

### PR DESCRIPTION
**Pull request by ribagi**
I will do more documentation tomorrow and how this works, but I am to tired. Here is the spreadsheet.

https://docs.google.com/spreadsheets/d/1Uuft4jo3chxOCXdfn8PJfizOfmqa8-5B7OeHdnHFqes/edit?usp=sharing

### CODE REVIEW

**Comment by ttk2** [comment]
no way this gets merged without a very long very good explanation.

**Comment by MonsWTF** [comment]
I think I can explain what's going on here:

Ribagi's adding a new factory, a Nether Compactor, to allow the Diamond and Iron Cauldrons to have even higher-tier versions of themselves.
Its namesake is what it does: compacts basic factory ingredients, such as potatoes, cacti, carrots, etc., and turns them into Crates using a wood icon (I think there's a slight typo on them...'Create of Carrot') to simulate the mass gathering of resources and packaging.

In order to be able to acquire said factory, you have to have operated Iron Cauldron and Diamond Cauldron recipes by a significant amount to collect Shards of Iron/Diamond, and after which you then gain access to 4 new recipes for both the Iron and Diamond cauldrons.

Quite literally, the aim of the Nether Compactor is to allow for ingredients to be stacked and collected and reduce the amount of micromanagement needed from the typical Diamond/Iron Cauldron that made them flounder in comparison to the extreme ease of Wheat. The spreadsheet probably tracks the efficiency in comparison of using regular Diamond recipes and the new ones.

While the idea is definitely interesting and awesome, I question the comparative advantage that a Compactor factory like this provides in its present state; and by this, I mean the micromanagement involved in creating the crates one at a time. Maybe having each recipe of the Nether Compactor do numerous crates, as opposed to 1 crate each run, would help to better outline the benefits.

**Comment by pruby** [comment]
Looks like each crate takes 1 stack of the ingredient to make, and allows very large scale exp recipes which produce more efficiently. New recipes are 32 times the size of the ones without packing.

Agreed, good idea but needs to produce more than one crate at a time to be worthwhile. This will make trading the ingredients for iron/diamond runs easier and give incentives for scaling up. A carrot farmer can sell carrot crates for exp. Maybe pack a single chest worth of any material in to 27 crates in a single recipe? Would make it much easier to operate by hand. Also, 60% efficiency boost for the diamond cauldron seems excessive - would make this just 15% on the iron and 30% on the diamond myself.

**Comment by MonsWTF** [comment]
Unfortunately though, for a carrot farmer to package any of the stuff he acquires, they'd need to own or be located near a Nether Compactor. After sitting down to think about it for a couple of days, the barrier of entry is quite high, maybe unnecessary. Perhaps the Compactor itself should be renamed and redesigned as a standalone item, with a custom crafting recipe so that the items can be unpacked if not used for the Cauldron? I could see that one having more player interest, since it would change the game of long-distance transport, especially with the amount of delivery companies competing.
I think the cauldron recipes are perfect, but like I said above, consider re-designing how the Nether Compactor works and is created.

**Comment by ttk2** [comment]
interesting principle, perhaps it should be discussed.

**Comment by MadeofMeat** [comment]
Is the primary purpose of the compactor to make cauldron use less "fiddly", or to make transportation of goods an order of magnitude cheaper?  If the latter, I would have to question whether that is really good for the game.

**Comment by MonsWTF** [comment]
@MadeofMeat 

The latter is something that I have decided to question recently, as it is an aspect that hasn't really been looked at ingame. There are factories to make experience, yes, but what about the transportation of goods other than Diamonds or Emeralds? It's fairly hard to transport things like carrots, potatoes, etc. across large landmasses. Have we not explored the idea of creating a moderately-expensive factory that consumes certain materials, like string, wood, ice, to 'package' said materials into more compact stacks of said item? And afterward, if those items aren't used for a machine that needs them, to 'unpack' them in a crafting grid back into their stacks of 64?

I could get to work on starting that kind of Factory(ies) assuming Ribagi and Ttk's fine with that idea, but I'd need some advice on where I would need to modify the crafting recipe to allow said items to unpack the way I was mentioning.

**Comment by pruby** [comment]
I really don't think we should be helping that much with transport. It's already possible to carry ridiculous amounts of stuff around in MC. When it does make sense is when you're extracting only part of something for a particular purpose - whatever it is in veges that makes exp can presumably be extracted and concentrated, etc.

I would make the compactor cheap and make it from regular materials though.

**Comment by ribagi** [comment]
I will lowered the Iron the 15% and the Diamond to 30% for their outputs. The Compactor import/outputs are boosted to 32 times. 

@pruby It isn't so much about transportation and more about fitting all the stuff inside the chest. By example, in Diamond 4 you'll need 178 slots. A double chest is like 58 slots. I also disagree with making it cheaper and with regular materials. This factory is designed to be an end game factory. By making this factory expensive and hard not only does it solve the transportation issue it also creates a next tear item and something people can aim for.

@MonsieurWTF I am fine with an unpacking factory. I was thinking of making one while creating this but after creating this and two 10 page essays in 4 days makes me tired. But rather making both the Compactor and Uncompactor(?) cheap, why not have the Compactor expensive and have the Uncompactor(?) cheap?

@MadeofMeat It is more of an attempt to build up the tech tree while keeping the original recipes in their original states.

**Comment by ttk2** [comment]
part of the issue seems that we can't incentive trade enough, maybe this
would help with that.

**Comment by MonsWTF** [comment]
@Ribagi the reason I was saying to make the Compactor cheaper was, in my previous posts, that 1) We have a lot of recently added high-end factories [Bastion, Iron Forge, Aspects, another Redstone factory, Explosives] 2) We're adding a Nether Teleportation Factory, two Potion factories, and this one as well.

I have two pieces that I am equally willing to vie for.

If we want to have a high-end Compactor, here are my concerns and suggestions:
- First off, the barrier of entry. You've added two new resources to the Iron and Diamond Cauldron, so that to build the factory you require the town/player to use the Iron Cauldron at minimum 160 times, and also needing to use the diamond cauldron 128 times. Assuming no immediate trading occurs for the byproducts from exp production, and assuming that most towns do not run both factories at the same time, it would probably be a while before we see someone start using these, and if the goal of the factory is to give a boost to Diamond/Iron Cauldron producers, then that boost won't be noticed until after lots of work with each.
- Reduce the barrier of entry by using existing items for the recipe. How about having the Compactor take 4 Framing, 16 Walls, 4 Flooring, and 2 Gearboxes, and anything else that may justify the cost? You can have the repair recipe take advantage of the Pure Ice or the Compact Ice, too.

If we would rather have a low-end Compactor, here are my suggestions:
- As opposed to having a 'one compactor fits all materials' kind of deal, we can have moderate-cost Compactors, each that deal with a specific variety of farmed goods. 

i.e. Crop Compactor for Wheat, Cocoa, Sugar, ...,
a Meat Compactor for Beef, Pork, Fish, ...,
Bio Compactor for Ferns, Vines, grass blocks, Flowers, ...,
a 'Hazardous materials' Compactor that stacks rotten flesh, Spider eyes, Mushrooms, and anything else for that category.
- The recipes for each of the compactors could be customized to the ingredients, but still have a low cost to make each so that building all four of them would be close to the cost of building a single High-end Compactor. That way, those who only farm only a quarter of the ingredients for a cauldron run can make a presence on the high-end part of the market, since then large amounts of Farm goods could be easily traded without maxing out their inventory, thus increasing the feasibility of trading over large distances.

I have a little bit more to say for whichever of these two versions people find more beneficial to Civcraft, but I'll hold off on that before this becomes a Berlin Wall. XD

**Comment by ariehkovler** [comment]
if the plan is to make the diamond cauldron less fiddly, probably the easiest thing would be for the 'compactor' to compact a full singlechest or doublechest of stuff into a varying amount of crates by recipe.

**Comment by MadeofMeat** [comment]
@MonsieurWTF, it's natural for it to be difficult and expensive to transport massive amounts of industrial goods.  The fact that people need to invest in mules, rails, minecart trains, caravan security, and so on is all good for the game.  If one player could carry everything that needed to be carried, you wouldn't have transport companies in the game like you do now.

@ttk2, when you say it is a goal to "incentivise trade", do you mean incentivising the player activity of seeking profitable trades and then transporting goods for profit?

Eliminating the cost of transporting goods would do the opposite, it would eliminate trading or running freight as a separate job within the economy.  Traders make their profits by looking for price differences to arbitrage, but in a world where goods transportation is instantaneous and effortless, prices in every city are the same: arbitrage opportunities don't exist.

I recommend waiting to see the results of the wood cauldron nerf, as I think this has already solved the problem of lack of trade.  If one-crop xp manufacture is eliminated, manufacturers have to rely on goods from many locations.  The transport industry in game is going to thrive as a result of this.  Making goods take up only 1/9 as much inventory space will eliminate 8/9 of this new activity.

**Comment by MonsWTF** [comment]
"If one player could carry everything that needed to be carried, you wouldn't have transport companies in the game like you do now."

I think there are a few misconceptions that are present here.....

1) People still need to travel. So, seeing horses and minecarts (and security for them, I guess?) won't just up and vanish.

2) Do you mind telling me how the impact of a stationary factory correlates to "instantaneous and effortless" trade?

3) I think you might have misread what I was saying before. This isn't about "massive amounts of industrial goods". This is about Raw Goods. Farming goods. Not Industrial, like netherrack, Nether quartz, metals and ores and other building materials that also take up lots of inventory space. I'm talking about good old cooked potatoes, nether warts, flowers, raw flesh, those kinds of things that may be restricted by travel distance and, due to their value, never have the right opportunity to justify delivery services? (Speaking of which, doesn't having a material even more compressed make it even more valuable for someone to steal, pushing the market to have MORE caravan security?)

4) Yes, the market has technically been affected by the wheat nerf only a couple of days ago, so the immediate changes to the Supply curve are not yet truly felt. But, it isn't going to be that long until the market has reached that stage and any further changes would be able to be directly correlated to the presence of a new factory.

**Comment by MadeofMeat** [comment]
@MonsieurWTF, regarding point 2, "effortless transport" would happen if a player were allowed to carry infinite carrots: carrot transport services would be as ubiquitious as the air we breathe, nobody would buy or sell them.  I gave the example of that extreme situation so we could use it as an end point, and predict by interpolation the effects of a change that takes us toward (not to) that extreme.  If carrot transport is nine times as easy, nine times fewer people/minecarts/mules will be involved in transport, carrot price differences between cities will be nine times closer, nine times fewer traders will be interested in shuttling loads of carrots around to arbitrage the carrot markets, and so on.

**Comment by staygroovy57** [comment]
I haven't had the time to pore over the fine details of this, but my first impression is very positive, I believe there is a good idea here. As always it's obviously going to be a matter of working out the balance, and the practical ways in which it can be used; as well as how it can help in keeping the game entertaining.

**Comment by ttk2** [comment]
bumping, final verdict seems positive? its in testing now on Civtest I
think I updated it with some corrections. any other questions, comments,
concerns?

**Pull request merged**
