### PR TITLE
Essential Still, Advanced Brewery & Potions

### PR DESCRIPTION
**Pull request by pruby**
This consists of two new factories which can produce some higher tier, multi-effect potions. The essential still refines the necessary distillates which are then used to make potions in the Advanced Brewery. 

Each potion combines higher tier positive effects with strong negative effects. They are intended to make the player play a specialised play style until they wear off or milk is used to end them early. They should give the user a decent advantage, but also carry a cost of specialisation. These potions are very expensive and time consuming to make, but have rather dramatic effects so should be thoroughly balance tested.

A small code change is included (with JAR) to make FactoryMod read potion effects on potion outputs and add them to the item stack.

New potions:
- Fortissimus Draught - Strength 3, Resistance 2, Slow 3 (3 minutes active, 2 minutes slow only)
- Extended Fortissimus Draught (6 minutes active, 2 minutes slow only)
- Elevative Draught - Speed 3, Jumping 2, Weakness 32 (can't inflict any melee damage) (3 minutes active, 2 minutes weak only)
- Extended Elevative Draught (6 minutes active, 2 minutes weak only)
- Potion of Haste - Haste 3, Hunger 8 (2 minutes active, 1 minute hunger only)

**Essential Still** - 512 Ferns, 64 Dead Bushes, 128 Lily Pads, 512 Bones, 128 Clownfish, 256 Pufferfish

```
Full repair for 16 Ferns, 16 Dead Bushes, 16 Lily Pads, 64 Bones, 16 Clownfish, 16 Pufferfish

64 Buffer Solution for 64 Glass Bottles, 1728 Bonemeal

8 Caenol for 8 Buffer Solution, 32 Dead Bush (non-renewable but easy-ish)

or 8 Caenol for 8 Buffer Solution, 64 Slime Balls (renewable but somewhat hard)

8 Tetrodotoxin for 8 Buffer Solution, 128 Pufferfish 

8 Ethereol for 8 Buffer Solution, 128 Soul Sand (non-renewable but easy)

or 8 Ethereol for 8 Buffer Solution, 64 Clownfish (renewable but very time consuming)

8 Pteridol for 8 Buffer Solution, 256 Ferns

8 Lilium Essence for 8 Buffer Solution, 32 Water Lily
```

**Advanced Brewery** - 512 Charcoal, 64 Caenol, 64 Tetrodotoxin, 64 Ethereol, 64 Pteridol, 64 Lilium Essence

```
Full repair for 128 Charcoal, 8 Caenol, 8 Tetrodotoxin, 8 Ethereol, 8 Pteridol, 8 Lilium Essence

8 Fortissimus Draught for 8 Caenol, 8 Tetrodotoxin

8 Extended Fortissimus Draught for 8 Caenol, 8 Tetrodotoxin, 8 Lilium Essence

8 Elevative Draught for 8 Ethereol, 8 Pteridol

8 Extended Elevative Draught for 8 Ethereol, 8 Pteridol, 8 Lilium Essence

8 Haste Potion for 64 Sugar, 8 Pteridol, 2 Tetrodotoxin, 6 Lilium Essence
```

### CODE REVIEW

**Comment by pruby** [comment]
Note - tested all recipes and that the potions work as intended on local Spigot server. Also confirmed that you can't avoid, diminish or shorten the negative effects using other potions of the same type (e.g. deliberately drink weak 1 to avoid weak 32 - the 32 takes priority whichever order taken in). Taking a potion with the same effect and same level and same duration resets the time.

**Comment by ttk2** [comment]
nice, I will have to ask what people think of the balance in the changelog
today.

**Comment by pruby** [comment]
Just fixed some errors in the recipe write-up above

**Comment by pruby** [comment]
Some balance adjustments made:
- Rename liquid calcium to buffer solution
- Replace bones in buffer solution recipe with bonemeal - don't encourage grinding quite so much.
- Halve fern requirement in Pteridol recipe - harder to grow renewably & harvest than I thought.
- Double up the distilled ingredients required for the haste potion so that all these potions take at least 2 ingredients in for each potion out, not 1.

**Comment by ribagi** [comment]
You know what this means?  A brewing factory!

**Comment by ribagi** [comment]
Or rather an alcohol factory

**Comment by MonsWTF** [comment]
Would these be all the potions available to the factory at start? Or is it possible we could suggest more potions to add to the list? (Inb4 super strength pots and limpwurt roots are added) If so I have a shitton of potential ideas and devlish things to suggest >:3

**Comment by pruby** [comment]
Any standard minecraft status effects can be easily applied, is all that these ones do (just higher level). Any other effect would require a separate plugin to implement the effect (triggered by drinking a potion with particular lore I expect).

**Comment by MonsWTF** [comment]
We......that's what I meant. Suggesting regular minecraft status effects that could be added to the list :s .

**Comment by pruby** [comment]
Is very easy to add more potions, coming up with the ingredients is the hardest bit. Go for it, will merge in to my pull if balanced :)

**Comment by ttk2** [comment]
Not really sure how people feel about these now.

**Comment by pruby** [comment]
Yeah, people haven't discussed this much. Few comments from people thinking they're underpowered, but would rather err on that side. Try it out then improve them if required?

**Pull request closed without merging**
